version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: auditaai-postgres
    environment:
      POSTGRES_DB: auditaai_db
      POSTGRES_USER: auditaai
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auditaai -d auditaai_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: