// Declarations to satisfy Next.js generated type imports (validator.ts)
// These wildcard module declarations prevent TypeScript from failing
// when Next generates imports that reference compiled .js paths.

declare module '*app/*/page.js';
declare module '*app/*/*/page.js';
declare module '*app/**/page.js';
declare module '*app/**/route.js';
declare module '*app/**/layout.js';
declare module '*app/**/route.ts';
declare module '*app/**/page.tsx';

declare module '*app/*/route.js';
declare module '*app/*/*/route.js';

// Catch-all fallback for any runtime-generated imports
declare module '*app/**';

// Also accept relative import forms generated by Next's validator
declare module '../../app/*/page.js';
declare module '../../app/*/*/page.js';
declare module '../../app/**/page.js';
declare module '../../app/**/route.js';
declare module '../../app/**/layout.js';
declare module '../../app/**';
