name: Playwright E2E and Auto-Fix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  e2e:
    name: Run Playwright E2E (local backend)
    name: Playwright E2E CI

    on:
      push:
        branches: [ main ]
      pull_request:
        branches: [ main ]
      workflow_dispatch: {}

    jobs:
      e2e:
        name: Playwright E2E (start frontend & backend)
        runs-on: ubuntu-latest
        container:
          image: mcr.microsoft.com/playwright:v1.56.1-focal
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Setup pnpm
            uses: pnpm/action-setup@v2
            with:
              version: '10'

          - name: Install root dependencies
            run: pnpm install --frozen-lockfile

          - name: Generate Prisma client (backend)
            working-directory: ./backend
            run: pnpm exec prisma generate || true

          - name: Start backend server
            run: |
              nohup node backend/server.js > /tmp/backend-ci.log 2>&1 &
              for i in {1..15}; do
                sleep 1
                if curl --silent --fail http://localhost:3001/health >/dev/null 2>&1; then
                  echo "backend ready"; break
                fi
                echo "waiting for backend..."
              done

          - name: Install frontend dependencies
            working-directory: frontend
            run: pnpm install --frozen-lockfile

          - name: Build frontend (pointing to local backend)
            working-directory: frontend
            env:
              BACKEND_INTERNAL_URL: http://localhost:3001
              NEXT_PUBLIC_BACKEND_URL: http://localhost:3001
            run: pnpm build

          - name: Start frontend (background)
            run: |
              nohup pnpm --cwd frontend start > /tmp/frontend.log 2>&1 &
              for i in {1..30}; do
                sleep 1
                if curl --silent --fail http://localhost:3000/ >/dev/null 2>&1; then
                  echo "frontend ready"; break
                fi
                echo "waiting for frontend..."
              done

          - name: Run Playwright E2E script against frontend
            run: TARGET_HOST=http://localhost:3000 node backend/scripts/playwright_bypass.cjs
